rm -rf *.id
python prepare_wallet_user1_org1.py
python prepare_wallet_user1_org2.py
python prepare_wallet_user1_org3.py
python prepare_wallet_user1_org4.py
python prepare_wallet_user1_org5.py
python prepare_wallet_user1_org6.py
python prepare_wallet_user1_org7.py
python prepare_wallet_user1_org8.py
